### PR TITLE
Add a way to configure how block types and blocks get combined in lan…

### PR DESCRIPTION
**Pull request by maximumpower55**
…g gen

### CODE REVIEW

**Review by woodiertexas — COMMENTED** [review]
This also supports languages where spaces aren't present?

**Comment by maximumpower55** [comment]
Yes? you just remove the space, I thought that would be pretty easy to know

**Comment by woodiertexas** [comment]
> Yes? you just remove the space

Oh ok

**Comment by woodiertexas** [comment]
On that note, this seems to be good to go.

**Pull request merged**
