### PR TITLE
Create uk_ua.json

### PR DESCRIPTION
**Pull request by unroman**
Ukrainian grammar doesn't allow me to make a better translation, but I also can't add exceptions to the translation myself, something like "architecture_extensions.minecrafr.end_stone_arch": "..."

maybe in the future, when I figure out how to add exceptions, I'll come back and do a better translation

### CODE REVIEW

**Comment by woodiertexas** [comment]
What do you mean by "exceptions"?

**Comment by falkreon** [comment]
Am I correct in understanding that in some cases the best translation would be `<adjective> <noun> <adjective>` like your endstone nubless rod translation? If so, I agree, exceptions would be a good workaround. We should have an update soon to make that possible.

**Comment by unroman** [comment]
@falkreon In fact, it's not so simple, some blocks have several words in their name, which is why they cannot be placed in front, as it happens in English, because in most Slavic languages, each word has a special ending that depends on the final word and therefore most translations should sound like «Arch from cracked stone bricks» — «Дуга з тріснутої кам'яної цегли» `<noun> <adjective> <adjective> <noun>`

**Comment by unroman** [comment]
when it comes to one word, it's very easy to do because I do it through combinations 
`Bamboo - «Бамбуков», Arch - «а дуга» = «Бамбукова дуга»`

**Comment by falkreon** [comment]
I see. I just wanted to understand the problem so I don't make the same mistake again in another mod. We'll get you the tools you need.

**Comment by falkreon** [comment]
Overrides work now - but I highly recommend keeping these best-effort individual keys around for compatibility with serverside things like Polydex.

Overrides are keyed on the "default" localization key that Minecraft would have generated for these blocks. So if the F3+H tooltip shows `architecture_extensions:minecraft/end_stone_arch`, the override localization key would be `block.architecture_extensions.minecraft.end_stone_arch`

Hope that helps! If you aren't feeling like adding additional translations right this second though we can go ahead and merge what you've put here.

**Pull request merged**
