### PR TITLE
Update & improve Actions workflows

### PR DESCRIPTION
**Pull request by Ampflower**
This allows actions the base CI to always run regardless of release, and allows for caching of Gradle's files.

This also includes a new publish workflow, which as long as the `MODRINTH` secret is supplied, will automatically upload the remapped jar to Modrinth when you make a release on GitHub.

### CODE REVIEW

**Comment by woodiertexas** [comment]
So does the workflow publish to modrinth on every commit or when I tell the workflow to do a publish run?

Also how would I work the "modrinth secret" thingy?

**Comment by Ampflower** [comment]
You have to explicitly create and publish a GitHub release for it to automatically upload to Modrinth.

As for setting the secret, you just need to copy your authorization token from the security tab under settings, create a new secret under the repo's settings, secrets, actions. Do note that the secret it requires is named `MODRINTH`.

**Comment by woodiertexas** [comment]
image
So this is how I'd set up the secrets thingy for modrinth?

**Comment by Ampflower** [comment]
Yes, that is all that's required.

**Comment by woodiertexas** [comment]
Thanks for the new workflow stuffs.

**Review by woodiertexas — APPROVED** [review]
Thanks for taking the time to put these together.

**Pull request merged**
